[package]
name = "rpi-os"
version = "0.1.0"
authors = ["esposm03 <36164633+esposm03@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.12"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.7.1"
volatile = "0.2.6"
